### ISSUE TITLE
Should we push this back to late spring/June 2015?

### ISSUE THREAD

**Issue by pixelyunicorn** [hshackers/PiperCon_old#2]
The only venue that has availability on December 20 is an empty warehouse in Jersey City, and December doesn't seem to be an ideal date with finals going on and preperations for Winter break.

Should we push this back to late spring/June?

**Comment by nsgomez** [comment]
Spring break or summer should be a more ideal time for everyone. I don't see any problem with pushing it back as long as ClawsConf gets additional promotion around then and people know it's being moved.

**Comment by zachlatta** [comment]
HackEDU (cc @jonleung) would be happy to help find a venue this winter
for this.

**Comment by pixelyunicorn** [comment]
@zachlatta @jonleung Can you get me in touch with someone as soon as possible? Would like to confirm a venue next week so I can reach out to sponsors and fill session slots. Thanks! :+1:

**Comment by zachlatta** [comment]
Yup! We'll get someone on it and have them reply to this thread.

**Comment by jonleung** [comment]
Hi @LabLayers, I think you're already working with @Mamadou888. He's going to look into the space at AlleyNYC & General Assembly!

**Comment by Mamadou888** [comment]
Hey Guys, So I've talked to Jonathan Leung of HackEdu and I'll help take lead on finding this venue.. Wish us luck!!! :)

**Comment by jonleung** [comment]
@Mamadou888 #hellyeah

**Comment by pixelyunicorn** [comment]
@jonleung :heart: You're the best!

**Comment by pixelyunicorn** [comment]
"ClawsConf" been pushed back to July. Closing issue.
